"""
V6 Mega Synthetic Data Generator
==================================
200+ unique templates per emotion category (8 labels).
Covers: casual, formal, short, long, ambiguous, social media, introspective.
Total: ~1600+ samples before augmentation.

Key improvements over V5:
- 3x more templates per category
- Harder edge cases (sentences that could go either way)
- More natural conversational phrasing  
- Variation in sentence length (2 words → 25+ words)
"""

import csv
import os
import random

OUTPUT_PATH = "data/v6_synthetic_dataset.csv"

templates = {
    # ================================================================
    # SADNESS (200) - grief, loss, hopelessness, loneliness, heartbreak
    # ================================================================
    "sadness": [
        # --- Grief & Loss ---
        "I keep reaching for my phone to text her before I remember she's gone.",
        "The house feels too quiet now.",
        "I smiled at our old photos and then just broke down crying.",
        "Everyone moved on but I'm still stuck in that moment.",
        "Some days I forget, and then it all comes crashing back.",
        "I just want one more conversation with them.",
        "Grief hits you in the strangest moments.",
        "I watched their favorite movie alone last night.",
        "I woke up forgetting, and then remembered, and that was the worst part.",
        "I miss who I used to be before all of this happened.",
        "The world keeps spinning but I feel frozen.",
        "I found their jacket in the closet and completely lost it.",
        "I keep dreaming about them and waking up hurts even more.",
        "I saw someone who looked like them and my heart stopped.",
        "The empty chair at the table still gets to me.",
        "Their birthday is next week and I don't know what to do with that.",
        "I drove past our old house and pulled over to cry.",
        "Every milestone I hit, I wish they were here to see it.",
        "I whispered happy birthday to an empty room.",
        "The holidays are the hardest without them here.",
        # --- Loneliness ---
        "Nobody checked in on me today.",
        "It hits different when you realize nobody noticed you were struggling.",
        "I've been alone for so long I've forgotten what connection feels like.",
        "I sat in the parking lot for twenty minutes because I couldn't face going inside.",
        "I feel invisible most days.",
        "I tried calling someone but nobody picked up.",
        "Loneliness isn't about being alone, it's about feeling alone in a room full of people.",
        "I went to a party and felt more alone than ever.",
        "I don't have a single person I could call right now.",
        "Nobody would notice if I disappeared for a week.",
        "I haven't had a real conversation in days.",
        "I eat dinner alone every night and it never gets easier.",
        "I used to have so many friends. Where did they all go.",
        "I wish someone would just ask me how I'm really doing.",
        "The weekends are the worst because there's nothing to distract from the loneliness.",
        # --- Hopelessness ---
        "I don't even have the energy to pretend I'm okay anymore.",
        "I feel like nothing is ever going to change.",
        "What's the point of trying when everything falls apart anyway.",
        "I keep waiting for things to get better but they don't.",
        "I've been stuck in this dark place for so long.",
        "I can't see a way out of this anymore.",
        "I'm so tired of feeling this way.",
        "I've tried everything and nothing works.",
        "I feel like I'm slowly fading away.",
        "Even the things that used to bring me joy feel empty now.",
        # --- Heartbreak ---
        "My chest literally aches from how much I miss them.",
        "I deleted all our messages and immediately regretted it.",
        "I can't believe the person I loved most could hurt me this deeply.",
        "I keep thinking about all the things I should have said.",
        "I trusted them with everything and they threw it away.",
        "I cried in the shower so nobody would hear.",
        "They moved on like I meant nothing.",
        "I found the ring I was going to give her.",
        "I keep our text thread open even though they'll never reply.",
        "Love isn't supposed to feel like this.",
        # --- Physical manifestation ---
        "I've been lying in bed all day and I just can't get up.",
        "My chest is heavy.",
        "I haven't really laughed in weeks.",
        "I can't eat. Everything tastes like nothing.",
        "I woke up crying and I don't even know why.",
        "There's a weight on my chest that never goes away.",
        "Even breathing feels heavy today.",
        "I spent the whole day in bed and accomplished nothing.",
        "I'm exhausted from pretending everything is fine.",
        "My pillow knows more about my feelings than anyone else.",
        # --- Short & direct ---
        "I feel hollow.",
        "Everything hurts.",
        "I miss them.",
        "I'm broken.",
        "I feel forgotten.",
        "Why me.",
        "I'm drowning.",
        "This hurts so much.",
        "I can't anymore.",
        "Empty.",
        # --- Long & introspective ---
        "It's been months since they left and I still set two places at the table sometimes before I catch myself.",
        "I thought I was getting better but then a song came on and I realized I hadn't moved at all.",
        "Nobody teaches you how to grieve. You just drown until you learn to float, and some days you go right back under.",
        "I used to love rainy days but now they just amplify the emptiness inside me.",
        "The worst part about this kind of sadness is that nobody can see it, so nobody knows to help.",
        "I drove around for hours because I didn't want to go home to an empty house.",
        "I feel like I'm watching my life from the outside and I can't find my way back in.",
        "I keep replaying the last conversation we had wondering if I could have changed anything.",
        "All I want is to go back to how things were before everything fell apart.",
        "Some days the sadness doesn't even feel like sadness anymore, it just feels like nothing.",
        "I went to our favorite restaurant alone and couldn't even order because everything reminded me of them.",
        "The world looks dimmer now, like someone turned down the brightness on everything.",
        "I miss being happy without having to try so hard to find it.",
        "I think the loneliest feeling is being surrounded by people who don't see you struggling.",
        "Every night I replay what went wrong and every morning I wake up exhausted from the answers I couldn't find.",
    ],

    # ================================================================
    # JOY (200) - happiness, excitement, pride, gratitude, hope, delight
    # ================================================================
    "joy": [
        # --- Achievement ---
        "I got the job after six months of rejection!",
        "I finished the marathon. I actually finished it!",
        "I passed my exam! All those late nights paid off.",
        "I got into my dream school!",
        "The whole room cheered when I finished my presentation.",
        "I got a promotion and I cried in the bathroom from happiness.",
        "I just got published. My words are out there.",
        "Walking out of that interview knowing I nailed it.",
        "I graduated today. Still can't believe it's real.",
        "I finally beat my personal best.",
        "After years of trying, I finally did it.",
        "They accepted my application!",
        "I hit my savings goal for the first time ever.",
        "My business just made its first profit.",
        "I solved the problem that's been bugging me for weeks.",
        # --- Connection & celebration ---
        "My daughter took her first steps today and I ugly cried.",
        "We stayed up talking until 3am and it felt like no time passed.",
        "We rescued a puppy and he already feels like family.",
        "I reconnected with an old friend and it felt like no time had passed.",
        "My whole family is together for the first time in years.",
        "She said yes!",
        "My kid drew a picture of our family and I'm keeping it forever.",
        "I caught fireflies with my kids tonight. Pure magic.",
        "My mom called just to say she's proud of me.",
        "I hugged my mom and didn't want to let go.",
        # --- Simple pleasures ---
        "Just had the best coffee of my life at this tiny place downtown.",
        "The sunset tonight made everything feel worth it.",
        "My dog learned a new trick and I'm unreasonably proud of him.",
        "I found a twenty dollar bill in my old jacket pocket.",
        "This pizza is absolutely incredible.",
        "I grew these tomatoes from seed and they're finally ripe.",
        "I heard my favorite song on the radio and danced in the kitchen.",
        "That first sip of coffee on a crisp morning is everything.",
        "The stars were unbelievable tonight.",
        "I just had the most incredible meal.",
        "Today was one of those rare perfect days.",
        "I perfected the recipe I've been working on for weeks.",
        # --- Emotional uplift ---
        "For the first time in months, I woke up looking forward to the day.",
        "I woke up to a text that made my whole day.",
        "Today I realized how far I've come and I'm proud of myself.",
        "Someone complimented my work and it made my entire week.",
        "I made someone laugh today and that filled me up.",
        "I left work feeling energized for once.",
        "Life surprised me with something beautiful today.",
        "Today I chose to be happy and for once it worked.",
        "I can't stop smiling after today.",
        "Everything just clicked into place today.",
        "I feel light and free for the first time in forever.",
        "The world looks different when you're happy.",
        "Music hit different today in the best way.",
        "Things are finally going right.",
        "Today felt like a movie scene in the best way.",
        # --- Gratitude ---
        "I'm so grateful for the small moments like this one.",
        "I woke up healthy, surrounded by love. What more could I want.",
        "My heart is overflowing with gratitude today.",
        "I don't deserve this much happiness but I'll take it.",
        "Looking around at my life and feeling incredibly thankful.",
        "Sometimes I forget how good I have it. Not today.",
        # --- General joy ---
        "I was laughing so hard my stomach hurt.",
        "I laughed until I had tears streaming down my face.",
        "I've been smiling all day for no reason.",
        "I feel genuinely happy right now and I want to hold onto this feeling.",
        "I'm genuinely optimistic about the future for once.",
        "I can't believe how lucky I feel right now.",
        "This is what freedom feels like.",
        "I danced in the rain today and didn't care who saw.",
        "I feel so alive right now.",
        "Every cell in my body is buzzing with happiness.",
        "I'm falling asleep happy and that's enough.",
        "I actually love my life right now.",
        "I'm so proud of the life I've built.",
        "Today was proof that good things still happen.",
        "I'm exactly where I'm supposed to be.",
        # --- Short & direct ---
        "Best day ever!",
        "I'm so happy!",
        "This is amazing!",
        "I can't stop smiling.",
        "Yes! Finally!",
        "I made it!",
        "Pure bliss.",
        "So proud.",
        "Absolutely thrilled.",
        "Over the moon right now.",
        "This is incredible!",
        "I'm on cloud nine.",
        "Euphoric.",
        "Best feeling ever.",
        "I'm elated.",
        # --- Long & descriptive ---
        "I just booked a trip to a place I've always dreamed of visiting and I can barely sit still with excitement.",
        "I made someone's day today and honestly it made mine even more than it made theirs.",
        "Sometimes the universe just gives you exactly what you need, and today was one of those days.",
        "I've never felt this content before and I want to bottle this feeling and keep it forever.",
        "I got the acceptance letter and I started screaming and crying at the same time.",
        "The kids put on a surprise show for me and it was the most adorable thing I've ever witnessed.",
        "I met someone who makes me want to be a better person, and that alone makes me happy.",
        "My garden is blooming beautifully this spring and I feel like I had a hand in creating something beautiful.",
    ],

    # ================================================================
    # LOVE (200) - deep affection, warmth, connection, tenderness, care
    # ================================================================
    "love": [
        # --- Romantic ---
        "Watching him sleep peacefully makes my heart so full.",
        "I found someone who makes silence comfortable.",
        "He remembered the small things, and that meant everything.",
        "I love the way he laughs when he thinks nobody is watching.",
        "The way she says my name makes the world stop.",
        "He always saves the last bite for me.",
        "She texted me 'got home safe' without me asking.",
        "I never knew love could feel this safe.",
        "I fell in love slowly and then all at once.",
        "I want to grow old with this person.",
        "She knows my fears and loves me anyway.",
        "He tells me I'm beautiful when I feel my worst.",
        "I look forward to the sound of your key in the door.",
        "He left his favorite shirt with me so I'd have something that smells like him.",
        "I love every version of you, past, present, and future.",
        "She is my home, no matter where we are.",
        "He makes my soul feel at peace.",
        "We built a life together and I'm so proud of it.",
        "I've never felt this understood before.",
        "The depth of what I feel for you scares me sometimes.",
        "Just hearing their voice makes everything better.",
        "I wake up grateful that I get to do life with you.",
        "You are my favorite person on this planet.",
        "I didn't know my heart could feel this full.",
        "You make even the mundane feel magical.",
        # --- Family ---
        "The way my grandmother holds my hand — I want to remember it forever.",
        "I look at my kids and I understand what unconditional means.",
        "My mom always knows exactly what to say.",
        "She braids my hair every morning and tells me stories.",
        "My dad still calls me his little girl even though I'm thirty.",
        "My baby grabbed my finger and my whole heart melted.",
        "I love the way this house smells when mom is cooking.",
        "Every wrinkle on her face tells a story of love.",
        "I wrote a letter to my dad telling him everything I never said.",
        "Seeing my parents hold hands after thirty years of marriage.",
        "My daughter fell asleep in my arms and I never wanted to move.",
        "I would give everything to protect this family.",
        "I look at old family photos and my chest fills with warmth.",
        "My kid said 'you're the best mom' and I melted.",
        "I carried her to bed even though my back was killing me because I love the way she clings to me.",
        # --- Friendship ---
        "She doesn't know it yet but she saved my life just by being there.",
        "My best friend drove four hours just because I sounded sad on the phone.",
        "I didn't know friendship could feel this deep.",
        "She stayed up all night with me even though she had work early.",
        "I trust this person with my whole heart.",
        "Being around them feels like coming home.",
        "She always believed in me, even when I didn't believe in myself.",
        "My sister is my best friend. Nobody knows me like she does.",
        "They make me feel seen in a way nobody else ever has.",
        "He stayed through the worst of it and never once complained.",
        "Her kindness heals parts of me I didn't know were broken.",
        "I would cross oceans for the people at this table.",
        "He learned my coffee order by heart.",
        "She held my hand during the scary part without me asking.",
        # --- General deep affection ---
        "I love how they light up when they talk about things they care about.",
        "Love isn't a word. It's the way you show up every single day.",
        "My heart belongs to these people at this dinner table.",
        "I love how you make even boring days feel special.",
        "I would do anything that makes you smile.",
        "My dog rests his head on my lap when I'm having a bad day.",
        "He held the door and waited for the old lady behind us.",
        "The way he looks at her when she's talking is everything.",
        "I've been loved in a way I never thought I deserved.",
        # --- Short ---
        "I love you so much.",
        "My heart is full.",
        "You mean the world to me.",
        "I adore you.",
        "You complete me.",
        "My everything.",
        "She's my person.",
        "I cherish this.",
        "Pure love.",
        "Soulmate.",
        # --- Long ---
        "I sat in the car after dropping her off at college and cried because I'm so proud and so scared and so full of love all at the same time.",
        "He doesn't say much but the way he fixes things around the house without being asked tells me everything I need to know.",
        "I watched her walk down the aisle and every doubt and fear I ever had dissolved in that moment.",
        "My grandmother still writes me letters by hand even though her hands shake, and each one feels like a treasure.",
        "I've never felt more at home than when I'm sitting on the couch doing absolutely nothing with you.",
    ],

    # ================================================================
    # ANGER (200) - frustration, injustice, resentment, rage, betrayal
    # ================================================================
    "anger": [
        # --- Betrayal ---
        "I trusted you and you used it against me.",
        "They lied to my face and expected me to just take it.",
        "You took advantage of someone who trusted you completely.",
        "You promised you'd change and you didn't. Again.",
        "You don't get to hurt me and then act like the victim.",
        "They gaslit me for months and now act like I'm the crazy one.",
        "They apologized but didn't mean a single word of it.",
        "They didn't just let me down, they betrayed me.",
        "You broke your word and that's not something I take lightly.",
        "I gave them everything and they gave me nothing.",
        "I confided in them and they used it against me.",
        # --- Injustice ---
        "They promoted the guy who takes credit for everyone else's work.",
        "The system is rigged against people like us.",
        "I'm tired of being the bigger person while they get away with everything.",
        "I work twice as hard for half the recognition.",
        "How is this fair. Please explain to me how this is fair.",
        "The rules only apply when it's convenient for them.",
        "Nobody held them accountable and that's the worst part.",
        "This is so unfair and nobody cares.",
        "The fact that nobody sees the problem IS the problem.",
        "The injustice of this situation is absolutely staggering.",
        # --- Frustration ---
        "How many times do I have to explain the same thing before someone listens.",
        "Don't tell me to calm down when you're the reason I'm upset.",
        "I am done being patient with people who don't respect my time.",
        "I've been screaming into the void and nobody is listening.",
        "Every time I try to express how I feel, I get shut down.",
        "You had one job and you couldn't even do that right.",
        "Nobody takes accountability anymore and it's infuriating.",
        "I'm so frustrated I could scream.",
        "Can you seriously not see how wrong this is.",
        "Stop making excuses and own up to what you did.",
        "This whole thing is a massive waste of my time.",
        "I'm so irritated by how incompetent this entire process is.",
        "I've been biting my tongue for way too long.",
        # --- Rage ---
        "I want to punch a wall right now.",
        "This situation makes my blood boil.",
        "I can feel the rage building and I'm trying not to explode.",
        "This makes me absolutely livid.",
        "I'm seething and I need to walk before I say something I regret.",
        "I was shaking with anger after that conversation.",
        "I'm so mad right now I can't even think straight.",
        "How dare they speak to me like that.",
        "I've never felt this much resentment toward someone.",
        "Everything is going wrong and I've had it.",
        # --- Work/Professional ---
        "I gave this company ten years and they let me go over email.",
        "They completely disregarded my feelings in that meeting.",
        "My boss took credit for my entire project.",
        "I stayed late every day this week and nobody even noticed.",
        "They changed the deadline without telling anyone.",
        "I was passed over again for someone less qualified.",
        # --- General ---
        "Sick of fake people.",
        "The audacity of some people is unbelievable.",
        "I've never been so disrespected in my life.",
        "They treat me like I'm disposable.",
        "How can someone be so selfish and not even realize it.",
        "I'm angry at a world that lets this happen.",
        "I'm done being nice to people who don't deserve it.",
        "I hate that I care this much about something that doesn't care about me.",
        "I'm over this. Completely over it.",
        "I'm angry and I have every right to be.",
        "I literally cannot deal with this level of stupidity.",
        "They ruined everything and they don't even feel bad about it.",
        "They knew exactly what they were doing.",
        "I got cut off three times in traffic and my patience is gone.",
        "I'm annoyed that I even have to deal with this.",
        "I'm furious at myself for letting this happen.",
        "I'm fed up with the double standards.",
        "I can't believe you just stood there and said nothing.",
        # --- Short ---
        "Disgusting.",
        "Unbelievable.",
        "How dare you.",
        "I'm livid.",
        "Absolutely furious.",
        "This is outrageous.",
        "I'm fuming.",
        "So disrespectful.",
        "I'm done.",
        "Unforgivable.",
    ],

    # ================================================================
    # FEAR (200) - anxiety, dread, panic, worry, phobia, overthinking
    # ================================================================
    "fear": [
        # --- Anxiety ---
        "What if they find out I have no idea what I'm doing.",
        "I can't stop thinking about all the ways this could go wrong.",
        "My anxiety has been through the roof lately.",
        "I'm anxious about things that haven't even happened yet.",
        "I had a panic attack in the grocery store today.",
        "My hands shake before every meeting.",
        "I woke up in a panic and couldn't remember why.",
        "I feel like something bad is about to happen.",
        "I can't breathe properly when I think about the future.",
        "The panic comes in waves and each one is worse.",
        "I'm one bad day away from completely falling apart.",
        "My chest tightens every time I walk into that building.",
        "I feel on edge all the time, like I'm waiting for something to go wrong.",
        "I had to pull over because my heart was racing so fast.",
        "The butterflies in my stomach have turned into a full tornado.",
        "I can't focus because the anxiety keeps pulling me under.",
        "My body is in constant fight-or-flight mode.",
        # --- Overthinking ---
        "I can't stop replaying that conversation in my head.",
        "I keep second-guessing every decision I make.",
        "I'm overthinking everything and I can't turn it off.",
        "My mind won't stop racing with worst case scenarios.",
        "What if I make the wrong decision and ruin everything.",
        "I lay awake at 3am worrying about things I can't control.",
        "I question every decision I make and it's exhausting.",
        "I keep imagining the worst and I can't stop.",
        "What if I'm wrong about everything.",
        "I froze during the presentation and now I can't stop replaying it.",
        "My brain won't shut off long enough for me to rest.",
        "I've been analyzing that text for twenty minutes wondering what they meant.",
        "Every possible outcome plays in my head on loop.",
        # --- Dread ---
        "Every time my phone rings late at night my heart drops.",
        "The doctor said they need to run more tests.",
        "I'm dreading tomorrow more than I can express.",
        "I can't shake this feeling of dread.",
        "The thought of starting over at my age is paralyzing.",
        "I feel dread in the pit of my stomach and it won't go away.",
        "Something feels off but I can't put my finger on it.",
        "I get this sinking feeling every Sunday night before Monday.",
        "The uncertainty is killing me more than the actual problem.",
        "I'm so stressed about money that I can't sleep.",
        "What if they don't come back.",
        # --- Vulnerability ---
        "I'm terrified of ending up alone.",
        "What if they find out I'm faking it.",
        "I'm scared to open that email.",
        "I'm afraid I'm turning into someone I don't want to be.",
        "I'm scared of disappointing the people who believe in me.",
        "I'm afraid to get close to anyone because everyone leaves eventually.",
        "I'm afraid to hope because the disappointment would destroy me.",
        "I feel unsafe even when logically I know I'm fine.",
        "I'm terrified of making a mistake that can't be undone.",
        "The fear of failure keeps me from even trying.",
        "I'm worried I'll never get over this.",
        "I don't know what's around the corner and that scares me.",
        # --- Physical symptoms ---
        "I keep checking the locks. I know I already checked but I can't stop.",
        "Sometimes I lie awake imagining the worst possible outcome.",
        "I've been having nightmares about failing.",
        "My body tenses up instinctively around certain people.",
        "I'm afraid to look at my bank account.",
        "Every small symptom sends me spiraling.",
        "I feel like I'm standing at the edge of a cliff.",
        "My palms are sweating just thinking about it.",
        "I haven't slept properly in days because of the worry.",
        "I feel my heart pounding even when nothing is happening.",
        # --- Short ---
        "I'm terrified.",
        "What if.",
        "I'm scared.",
        "I can't breathe.",
        "Please don't.",
        "I'm panicking.",
        "So anxious.",
        "I'm worried sick.",
        "Something's wrong.",
        "I'm dreading it.",
        # --- Long ---
        "I've been avoiding that conversation for weeks because every possible outcome I imagine ends badly and I can't handle one more thing going wrong.",
        "I spent the whole day at work pretending everything was fine but inside I was barely holding it together because I'm convinced they're going to let me go.",
        "I can't focus on anything because my brain keeps going to the darkest possible scenarios and I'm exhausted from trying to talk myself out of them.",
        "I'm worried sick about my parents' health and every phone call from home makes my heart stop for a second.",
        "I feel like I'm walking on eggshells constantly and I don't know how much longer I can keep this up.",
    ],

    # ================================================================
    # SURPRISE (200) - shock, astonishment, disbelief, unexpected
    # ================================================================
    "surprise": [
        # --- Shock ---
        "Wait, WHAT? You're telling me this NOW?",
        "I opened the door and everyone was there. I had no clue.",
        "I can't believe this is actually happening.",
        "My jaw literally dropped when I heard the news.",
        "I looked at the results three times because I didn't believe them.",
        "I got the call and I was so shocked I couldn't even respond.",
        "I just stood there, mouth open, completely dumbfounded.",
        "That was the last person I expected to see at that event.",
        "I audibly gasped. In public.",
        "I'm shook.",
        "Hold on, did I hear you right?",
        "You're kidding me right now. Seriously?",
        "Wow. I need a minute to process this.",
        "Nobody saw that coming.",
        "That's wild. Absolutely wild.",
        "What in the world.",
        "I'm stunned.",
        "Did that really just happen or am I dreaming.",
        "Wait... you're serious? This isn't a joke?",
        "I can barely wrap my head around what just happened.",
        "What just happened.",
        "No way. No way no way no way.",
        "That's the most unexpected thing I've heard all year.",
        "I literally froze when they told me.",
        "My brain short-circuited for a second there.",
        # --- Positive surprise ---
        "They actually apologized. I'm genuinely speechless.",
        "My test results came back completely normal. I was bracing for the worst.",
        "I won the raffle. I never win anything.",
        "I walked out of the exam feeling defeated and turns out I aced it.",
        "I got a message from someone I never thought I'd hear from again.",
        "I checked my bank account and there's an extra deposit I can't explain.",
        "The twist ending was incredible. I did not see it coming.",
        "My quiet coworker just delivered the most powerful speech I've ever heard.",
        "I got the email and had to read it five times to make sure.",
        "Came home to a surprise I will never forget.",
        "That revelation changed everything I thought I knew.",
        "I opened the letter and my whole world shifted.",
        "They threw me a surprise party and I genuinely had zero clue.",
        "I just found out I've been accepted and I'm still processing.",
        "The plot twist was incredible, completely blindsided me.",
        # --- Neutral/negative surprise ---
        "I never expected to hear from them again after all these years.",
        "He showed up at my doorstep with flowers after ten years apart.",
        "I just found out I have a half-sibling I never knew about.",
        "Plot twist — the quiet kid in class is a published author.",
        "Out of nowhere the whole office started clapping.",
        "I opened a book from my childhood and a note from my father fell out.",
        "Life just threw me the most unexpected curveball.",
        "She told me she's pregnant and I did NOT see that coming.",
        "My neighbor just casually mentioned they used to be a spy.",
        "Someone I ghosted five years ago just showed up at my work.",
        "That was the most unexpected thing that's happened to me all year.",
        "I walked into the room and it was completely transformed.",
        "I turned around and there he was, completely out of nowhere.",
        "The plot twist in that movie blew my mind.",
        "This is the kind of thing you read about but never expect to experience.",
        # --- Short ---
        "Whoa.",
        "No way!",
        "I'm speechless.",
        "Unexpected.",
        "Did NOT see that coming.",
        "I'm floored.",
        "Mind blown.",
        "Blindsided.",
        "Shocked.",
        "That twist though.",
        # --- Long ---
        "I was going about my normal day when I got a phone call that completely changed the trajectory of my entire life.",
        "I'm still trying to process what I just witnessed, my brain literally cannot compute it.",
        "I hadn't heard from them in over five years and then they just showed up like no time had passed at all.",
        "I spent months preparing for the worst-case scenario and then the outcome was the complete opposite of what I expected.",
        "I sat there staring at my phone for a solid five minutes because the message I just received makes absolutely no sense.",
    ],

    # ================================================================
    # BORED (200) - apathy, restlessness, monotony, numbness, ennui
    # ================================================================
    "bored": [
        # --- Apathy & Numbness ---
        "I watched the news and felt absolutely nothing.",
        "People keep asking how I am and I just shrug because I genuinely don't know.",
        "I ate because it was lunchtime, not because I was hungry.",
        "Things that used to excite me just feel like noise now.",
        "I'm not sad. I'm not happy. I'm just here.",
        "Someone told me great news and I couldn't even fake a reaction.",
        "I feel completely flat. No highs, no lows, just nothing.",
        "I feel numb to everything.",
        "Nothing matters and I can't be bothered to care about that fact.",
        "I feel blank. Like a factory reset happened on my personality.",
        "Every conversation feels like it's happening underwater.",
        "I feel emotionally numb and physically restless at the same time.",
        "Nothing excites me. Nothing annoys me. I'm just flat.",
        "I don't feel anything at all and I can't tell if that's okay or not.",
        "I feel like my personality shut off today.",
        "Just going through the motions.",
        "I just exist. That's the whole update.",
        "Autopilot mode activated.",
        "I'm somewhere between lazy and lifeless.",
        "I feel like furniture. Just here, taking up space.",
        # --- Restlessness ---
        "I've opened every app on my phone twice and nothing interests me.",
        "I need something to happen. Anything.",
        "I'm so understimulated my brain is practically begging for input.",
        "I need stimulation. This silence is killing me.",
        "I started three different activities and lost interest in all of them.",
        "I have hobbies but none of them sound appealing right now.",
        "I feel like I should be doing something but I don't know what.",
        "I'm pacing around my apartment like a caged animal.",
        "I keep picking things up and putting them back down.",
        "I went for a walk, came back, and I'm still bored.",
        "I'm restless but I can't think of anything that would fix it.",
        "I'm in a rut and I can't climb out.",
        "I'm understimulated and overstimulated at the same time somehow.",
        "I feel like I'm running on empty but also have nowhere to go.",
        # --- Monotony ---
        "Same routine, same walls, same nothing.",
        "Every day feels like a carbon copy of the one before it.",
        "The days blur into each other when nothing changes.",
        "Is it possible to be bored of being bored?",
        "Sunday afternoon and I'm just killing time until Monday.",
        "My weekend plans: absolutely nothing. Not by choice.",
        "I'm trapped in the most boring day of my life.",
        "There's nothing to look forward to this week.",
        "Today is forgettable and I haven't even finished it yet.",
        "My day has been a flat line. Literally nothing happened.",
        "Out of all the days that have existed, this is definitely one of them.",
        "If boredom was a sport I'd be a world champion.",
        "The most interesting thing today was a notification about a software update.",
        # --- Screen/Phone boredom ---
        "I scrolled through my phone for three hours and can't remember a single thing.",
        "I've been flipping channels for thirty minutes and nothing holds my attention.",
        "I've refreshed the same page fifteen times hoping for something new.",
        "My screen time report is embarrassing and I don't even remember any of it.",
        "I've been doomscrolling for two hours straight.",
        "I have access to literally all of human knowledge and I'm still bored.",
        "I've been playing one game on repeat because I can't think of anything else.",
        "I keep opening the fridge even though I know nothing new is in there.",
        "I've read the same paragraph four times because my brain keeps drifting.",
        # --- Low energy ---
        "Too tired to do anything fun but too bored to sleep.",
        "I'm literally just lying here rotting.",
        "I've been staring at this wall for twenty minutes and I don't care.",
        "My energy is at absolute zero today.",
        "I just don't feel like doing anything at all.",
        "Brain empty. No thoughts. Just existing.",
        "I can't even think of something I want to do.",
        "Nothing sounds appealing right now.",
        "I have a list of things to do but zero motivation to do any of them.",
        "I could do something productive but I just don't want to.",
        "I woke up and immediately wanted to go back to sleep. Not tired, just uninterested.",
        "I'm not doing anything and I don't plan to.",
        "I tried being productive. Lasted about four minutes.",
        "All the shows I used to love seem boring now.",
        "I'm so checked out right now.",
        "I sat through a two-hour meeting and retained zero percent of it.",
        # --- Existential boredom ---
        "I feel like my life is buffering.",
        "My brain is running at 5 percent capacity today.",
        "My brain feels like it's running in power saving mode.",
        "Sitting here wishing life had a fast forward button.",
        "Even my thoughts are boring right now.",
        "I feel like time stopped but in the most uninteresting way possible.",
        "My attention span is officially nonexistent.",
        "I've been waiting for inspiration and it clearly took the day off.",
        "I'm so bored I started organizing my sock drawer.",
        "I'm literally watching the clock. It's not even moving.",
        "I stared at a menu for ten minutes because nothing appealed to me.",
        "The highlight of my day was watching the microwave timer count down.",
        "I yawned so hard a tear came out and that was the most I've felt all day.",
        "I'm counting ceiling tiles. That's where I'm at.",
        "I tried meditating but my brain refused to cooperate.",
        "I feel like I'm wasting my time but also don't care enough to stop.",
        # --- Social boredom ---
        "I need a hobby. Or a friend. Or a crisis. Something.",
        "Honestly I'd welcome a minor inconvenience just for the variety.",
        "I'm so bored I could watch paint dry and it would be an improvement.",
        "I stuck in an infinite loop of doing nothing and feeling guilty about it.",
        "I'm not depressed. I'm just overwhelmingly bored.",
        "Everything feels meh.",
        "The world is happening outside and I'm here doing absolutely nothing.",
        "I've been wearing the same sweatpants for three days because what's the point.",
        "I feel like I'm existing but not really living today.",
        # --- Short ---
        "So bored.",
        "Kill me now.",
        "Nothing to do.",
        "Meh.",
        "This is dull.",
        "Yawn.",
        "Ugh, bored.",
        "I'm so done with today.",
        "Zero motivation.",
        "I got nothing.",
    ],

    # ================================================================
    # NEUTRAL (200) - calm, balanced, focused, observational, routine
    # ================================================================
    "neutral": [
        # --- Routine ---
        "It was an average day. Nothing great, nothing bad.",
        "I finished what I needed to do and went home.",
        "The weather is fine today.",
        "I had leftovers for dinner. They were alright.",
        "Work was normal. Nothing worth mentioning.",
        "I ran some errands and now I'm back.",
        "I watched some TV after work.",
        "I cooked dinner and cleaned up.",
        "The meeting went as expected.",
        "Just another Tuesday.",
        "Had a quiet morning reading the paper.",
        "I caught the earlier train today.",
        "Nothing to report. Just a regular day.",
        "I made my bed, brewed some tea, and started working.",
        "The commute was smooth today.",
        "I ate breakfast, brushed my teeth, and started my day.",
        "The morning was slow. The afternoon was productive.",
        "I watered the plants and checked mail.",
        "I had a conversation with a colleague about work procedures.",
        "I cooked a new recipe. It turned out decent.",
        # --- Calm & Balanced ---
        "I'm okay. Not great, not bad, just okay.",
        "I'm just going with the flow.",
        "Everything is stable. Steady.",
        "I don't really have strong feelings about it either way.",
        "It is what it is.",
        "I feel calm and present right now.",
        "I'm content with how things are going.",
        "I don't need anything right now — everything is fine as is.",
        "I'm at peace with where things stand.",
        "I'm in a steady head space today.",
        "My mind is clear.",
        "I'm feeling pretty balanced right now.",
        "I have no complaints today.",
        "I'm good. Nothing feels urgent or overwhelming.",
        "I feel grounded today.",
        "I'm relaxed and present.",
        "My energy is even today. Not high, not low.",
        "I feel stable and that's enough.",
        "I'm okay with the pace of things right now.",
        "I'm not in a rush. Everything can wait.",
        # --- Focused & Productive ---
        "I handled the tasks on my to-do list efficiently.",
        "I spent the morning focusing on deep work.",
        "The project is on track and I'm not stressed about it.",
        "Just finished yoga and I feel balanced.",
        "I meditated for ten minutes and I feel centered.",
        "I had a quiet evening at home and it was exactly what I needed.",
        "Things are going according to plan.",
        "Just maintaining my routine.",
        "I completed the task without any issues.",
        "My focus was good today.",
        "Everything feels manageable today.",
        "I learned something new today.",
        "I cleaned the apartment and it feels refreshing.",
        "I'm performing well at work but not over-exerting myself.",
        "Everything is operating as usual.",
        "I finished my workout and feel composed.",
        "I caught up on emails and cleared my inbox.",
        "I'm focused. My work is flowing well.",
        # --- Observational ---
        "I went for a walk. It was nice.",
        "I noticed the trees are changing color.",
        "I observed the birds in the yard this morning.",
        "Just thinking about what to have for lunch.",
        "I read some articles during my break.",
        "I took a walk around the block at lunch. Fresh air was nice.",
        "Currently listening to music and organizing my desk.",
        "Took the scenic route today. It was pleasant.",
        "I read a chapter of my book during lunch.",
        "I had green tea and journaled for a few minutes.",
        # --- Reflective ---
        "I'm reflecting on the day and it was pretty uneventful.",
        "Looking forward to a quiet weekend.",
        "Just living day to day.",
        "Just taking things one step at a time.",
        "Took a slow morning and it set a good tone for the day.",
        "Nothing noteworthy, which is sometimes the best kind of day.",
        "Just doing what needs to be done.",
        "I don't feel one way or another about it.",
        "All in all, a fairly standard day.",
        "I'm present but not particularly engaged or disengaged.",
        # --- Short ---
        "Fine.",
        "Okay.",
        "Normal day.",
        "All good.",
        "Same old.",
        "Not bad.",
        "Decent.",
        "Fair enough.",
        "Alright.",
        "Can't complain.",
        # --- Long ---
        "I spent the day doing what I normally do — woke up, worked, walked the dog, made dinner, and now I'm winding down.",
        "Everything today moved at a steady, predictable pace and honestly that's exactly what I needed.",
        "I'm looking at my day and realizing it was pretty standard — nothing exciting, nothing terrible, just a regular Wednesday.",
        "I had an uneventful morning, a moderately productive afternoon, and I'm ending the day feeling neither good nor bad.",
        "I'm just existing in a very ordinary way today and that feels perfectly fine.",
    ],
}


def generate():
    rows = []
    for label, texts in templates.items():
        for text in texts:
            rows.append({"text": text, "label": label})

    random.seed(42)
    random.shuffle(rows)

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["text", "label"])
        writer.writeheader()
        writer.writerows(rows)

    print(f"✅ Generated {len(rows)} V6 synthetic samples → {OUTPUT_PATH}")
    print(f"\nLabel distribution:")
    from collections import Counter
    counts = Counter(r["label"] for r in rows)
    for label, count in sorted(counts.items()):
        print(f"  {label:15s} {count}")
    print(f"\n  TOTAL: {len(rows)}")


if __name__ == "__main__":
    generate()
