"""
V5 Synthetic Data Generator
============================
Generates rich, diverse synthetic data for 8 CONSOLIDATED emotion labels.
Each category gets 150+ high-quality samples with natural, conversational English.
No repetitive wording. Mix of short and long inputs.
"""

import csv
import os
import random

OUTPUT_PATH = "data/v5_synthetic_dataset.csv"

# ============================================================
# TEMPLATES PER EMOTION (150+ each for bored/neutral, 80+ for others)
# ============================================================

templates = {
    # ============================
    # SADNESS - grief, loss, hopelessness, loneliness, heartbreak
    # ============================
    "sadness": [
        "I keep reaching for my phone to text her before I remember she's gone.",
        "The house feels too quiet now.",
        "I smiled at our old photos and then just broke down crying.",
        "Everyone moved on but I'm still stuck in that moment.",
        "I don't even have the energy to pretend I'm okay anymore.",
        "It hits different when you realize nobody noticed you were struggling.",
        "I sat in the parking lot for twenty minutes because I couldn't face going inside.",
        "Some days I forget, and then it all comes crashing back.",
        "I miss who I used to be.",
        "I've been lying in bed all day and I just can't get up.",
        "Nobody checked in on me today.",
        "I cried in the shower so nobody would hear.",
        "Everything reminds me of what I lost.",
        "I feel like I'm drowning in my own thoughts.",
        "The holidays are the hardest without them.",
        "I faked a smile at work but inside I was falling apart.",
        "I can't listen to that song anymore without tearing up.",
        "It's been months and the pain hasn't gotten any smaller.",
        "I just want one more conversation with them.",
        "I feel hollow inside, like something important is missing.",
        "Grief hits you in the strangest moments.",
        "I watched their favorite movie alone last night.",
        "Loneliness isn't about being alone, it's about feeling alone in a room full of people.",
        "I deleted all our messages and immediately regretted it.",
        "I keep thinking about all the things I should have said.",
        "I don't want to go out because everything out there reminds me of better times.",
        "My chest literally aches from how much I miss them.",
        "I used to love rainy days. Now they just make me feel emptier.",
        "Nobody teaches you how to grieve. You just drown until you learn to float.",
        "I thought I was getting better but today proved me wrong.",
        "I woke up forgetting, and then remembered, and that was the worst part.",
        "I feel like a burden to everyone around me.",
        "The world keeps spinning but I feel frozen.",
        "I can't believe the person I loved most could hurt me this deeply.",
        "Even good things feel heavy right now.",
        "I went to our favorite restaurant alone and couldn't even order.",
        "I just want to feel something other than this emptiness.",
        "I keep waiting for things to get better, but they don't.",
        "I'm so tired of feeling this way.",
        "I haven't really laughed in weeks.",
        "I feel like I'm watching my life from the outside.",
        "There's a weight on my chest that never goes away.",
        "I lost my best friend and I don't know how to exist without them.",
        "I thought time heals everything but it's been years.",
        "I woke up crying and I don't even know why.",
        "All I want is to go back to how things were before.",
        "I'm trying so hard but nothing feels like enough.",
        "Sometimes the sadness creeps in and I can't stop it.",
        "I saw a family laughing together at the park and it made me cry.",
        "I feel like nobody really knows me anymore.",
        "My heart feels bruised.",
        "I spent the whole day in bed and accomplished nothing.",
        "I feel invisible.",
        "I smiled today and it felt foreign on my face.",
        "The worst part is knowing it could have been different.",
        "I don't feel like I belong anywhere.",
        "I just feel really, really low today.",
        "I tried calling someone but nobody picked up.",
        "I feel like I'm mourning someone who's still alive.",
        "I keep hoping to feel normal again but I've forgotten what that means.",
        "Everything feels gray.",
        "I don't think anyone would notice if I just disappeared.",
        "I watched a sunset alone and wished I had someone to share it with.",
        "I cried on the bus today and nobody looked twice.",
        "I'm exhausted from pretending everything is fine.",
        "I miss being happy without trying.",
        "I used to love this time of year.",
        "I keep checking my phone even though I know no one will text.",
        "I feel forgotten.",
        "Every night I replay what went wrong.",
        "I lost myself somewhere along the way.",
        "There's a sadness deep inside me that I can't reach to fix.",
        "I don't know how to ask for help without feeling weak.",
        "Even breathing feels heavy today.",
        "My pillow knows more about my feelings than anyone else.",
        "I feel like I'm slowly fading away.",
        "I drove around for hours because I didn't want to go home to an empty house.",
        "I failed at something I really cared about.",
        "The silence in this apartment is deafening.",
    ],

    # ============================
    # JOY - happiness, excitement, pride, gratitude, hope
    # ============================
    "joy": [
        "I got the job after six months of trying!",
        "My daughter took her first steps today and I cried happy tears.",
        "Just had the best coffee of my life at this tiny place downtown.",
        "We stayed up talking until 3am and it felt like no time passed.",
        "I finished the marathon. I actually did it.",
        "The sunset tonight made everything feel worth it.",
        "My dog learned a new trick and I'm unreasonably proud.",
        "For the first time in months, I woke up looking forward to the day.",
        "She said yes!",
        "I heard my favorite song on the radio and danced in the kitchen.",
        "Today was one of those rare perfect days.",
        "I was laughing so hard my stomach hurt.",
        "My kid drew a picture of our family and I'm keeping it forever.",
        "I just booked a trip to a place I've always dreamed of visiting.",
        "That feeling when you help someone and they genuinely light up.",
        "I passed my exam! All those late nights finally paid off.",
        "I can't stop smiling after today.",
        "We rescued a puppy and he already feels like family.",
        "I woke up to a text that made my whole day.",
        "Today I realized how far I've come and I'm proud of myself.",
        "Life surprised me with something beautiful today.",
        "This pizza is absolutely incredible, I'm in heaven.",
        "I found a twenty dollar bill in my old jacket pocket.",
        "My mom called just to say she's proud of me.",
        "The whole room cheered when I finished my presentation.",
        "I laughed until I had tears streaming down my face.",
        "Everything just clicked into place today.",
        "I left work feeling energized for once.",
        "I reconnected with an old friend and it felt like no time had passed.",
        "I grew these tomatoes from seed and they're finally ripe.",
        "My hard work actually made a difference and people noticed.",
        "The kids put on a surprise show for me and it was adorable.",
        "I can't believe how lucky I feel right now.",
        "Someone complimented my work and it made my entire week.",
        "I made someone laugh today and that filled me up.",
        "I'm genuinely happy right now and I want to hold onto this feeling.",
        "I perfected the recipe I've been working on for weeks.",
        "Walking out of that interview knowing I nailed it. Best feeling.",
        "I'm so grateful for the small moments like this one.",
        "Everything tastes better when you're in a good mood.",
        "I got a promotion and I cried in the bathroom from happiness.",
        "Today I chose to be happy and for once it worked.",
        "My whole family is together for the first time in years.",
        "I just had the most incredible meal.",
        "I met someone who makes me want to be a better person.",
        "I've been smiling all day for no reason.",
        "Got the acceptance letter. I'm screaming.",
        "My garden is blooming beautifully this spring.",
        "That moment when you realize everything worked out.",
        "I danced in the rain today and didn't care who saw.",
        "I feel light and free for the first time in forever.",
        "Sometimes the universe just gives you exactly what you need.",
        "I feel so alive right now.",
        "Little moments of pure happiness are what I live for.",
        "I just want to bottle this feeling and keep it forever.",
        "My heart is overflowing with gratitude today.",
        "Today was proof that good things still happen.",
        "I made someone's day and it made mine too.",
        "I graduated today. Still can't believe it's real.",
        "This moment right here — this is what matters.",
        "I woke up healthy, surrounded by love. What more could I want.",
        "I actually love my life right now and that's new for me.",
        "I'm so proud of the life I've built.",
        "The world looks different when you're happy.",
        "That first sip of coffee on a crisp morning is everything.",
        "I caught fireflies with my kids tonight. Pure magic.",
        "I just got published. My words are out there in the world.",
        "Music hit different today in the best way possible.",
        "Every cell in my body is buzzing with happiness.",
        "I've never felt this content before.",
        "The stars were unbelievable tonight and I just sat there in awe.",
        "Things are finally going right.",
        "I hugged my mom and didn't want to let go.",
        "I'm exactly where I'm supposed to be.",
        "This is what freedom feels like.",
        "I got into my dream school!",
        "Today felt like a movie scene in the best way.",
        "I'm falling asleep happy and that's enough.",
        "I feel genuinely optimistic about the future for once.",
    ],

    # ============================
    # LOVE - affection, warmth, tenderness, deep connection, care
    # ============================
    "love": [
        "Watching him sleep peacefully makes my heart so full.",
        "I would cross oceans for the people sitting at this table.",
        "She doesn't know it yet but she saved my life just by being there.",
        "The way my grandmother holds my hand — I never want to forget.",
        "I found someone who makes silence comfortable.",
        "He remembered the small things, and that meant everything.",
        "My best friend drove four hours just because I sounded sad.",
        "I look at my kids and finally understand the word unconditional.",
        "She held my hand during the scary part without me asking.",
        "I love the way he laughs when he thinks nobody is watching.",
        "My mom always knows exactly what to say.",
        "She stayed up all night with me even though she had work early.",
        "The way he looks at her when she's talking is everything.",
        "I wrote a letter to my dad telling him everything I never said.",
        "I love that we can sit in silence and it doesn't feel weird.",
        "Seeing my parents hold hands after thirty years of marriage.",
        "He always saves the last bite for me.",
        "My dog rests his head on my lap when I'm having a bad day.",
        "She texted me 'got home safe' without me asking.",
        "I trust this person with my whole heart.",
        "Being around them feels like coming home.",
        "She always believed in me, even when I didn't believe in myself.",
        "He learned my coffee order by heart.",
        "I would do anything that makes you smile.",
        "I never knew love could feel this safe.",
        "She braids my hair every morning and tells me stories.",
        "My dad still calls me his little girl even though I'm thirty.",
        "I love how they light up when they talk about things they care about.",
        "The way she says my name makes the world stop.",
        "I look at old family photos and my chest fills with warmth.",
        "He held the door and waited for the old lady behind us.",
        "I love how you make even boring days feel special.",
        "My sister is my best friend. Nobody knows me like she does.",
        "They make me feel seen in a way nobody else ever has.",
        "He stayed through the worst of it and never once complained.",
        "I fell in love slowly and then all at once.",
        "I want to grow old with this person.",
        "She knows my fears and loves me anyway.",
        "My baby grabbed my finger and my whole heart melted.",
        "I love the way this house smells when mom is cooking.",
        "He tells me I'm beautiful when I feel my worst.",
        "I didn't know friendship could feel this deep.",
        "I would give everything to protect this family.",
        "Her kindness heals parts of me I didn't know were broken.",
        "I've never felt this understood before.",
        "We built a life together and I'm so proud of it.",
        "The way he hugs me — like I'm the most important person in the world.",
        "I love you isn't enough to describe how I feel.",
        "Every wrinkle on her face tells a story of love.",
        "I'm grateful every day that we found each other.",
        "She walked into my life and suddenly everything made sense.",
        "We've been through hell and back and we're still standing together.",
        "I love every version of you, past, present, and future.",
        "He makes my soul feel at peace.",
        "She is my home, no matter where we are.",
        "My heart belongs to these people at this dinner table.",
        "The depth of what I feel for you scares me sometimes.",
        "He left his favorite shirt with me so I'd have something that smells like him.",
        "She's not just my partner; she's my whole world.",
        "Love isn't a word. It's the way you show up every single day.",
    ],

    # ============================
    # ANGER - frustration, injustice, resentment, rage, betrayal
    # ============================
    "anger": [
        "They promoted the guy who takes credit for everyone else's work.",
        "I trusted you and you used it against me.",
        "How many times do I have to explain before someone listens.",
        "The system is rigged against people like us.",
        "I'm tired of being the bigger person while they get away with everything.",
        "Don't tell me to calm down when you're the reason I'm upset.",
        "They knew exactly what they were doing.",
        "I gave this company ten years and they let me go over email.",
        "Sick of fake people.",
        "I can't believe you just stood there and said nothing.",
        "Every time I try to express how I feel, I get shut down.",
        "You had one job and you couldn't even do that right.",
        "I'm furious at myself for letting this happen.",
        "They lied to my face and expected me to just take it.",
        "This is so unfair and nobody cares.",
        "I've been biting my tongue for way too long.",
        "You took advantage of someone who trusted you completely.",
        "I am done being patient with people who don't respect my time.",
        "The audacity of some people is unbelievable.",
        "I've never been so disrespected in my life.",
        "How dare they speak to me like that.",
        "I've been screaming into the void and nobody is listening.",
        "They ruined everything and they don't even feel bad about it.",
        "I want to punch a wall right now.",
        "This situation makes my blood boil.",
        "You promised you'd change and you didn't. Again.",
        "I'm fed up with the double standards.",
        "They treat me like I'm disposable.",
        "I can feel the rage building and I'm trying not to explode.",
        "How can someone be so selfish and not even realize it.",
        "I'm angry at a world that lets this happen.",
        "You don't get to hurt me and then act like the victim.",
        "I'm so frustrated I could scream.",
        "They gaslit me for months and now act like I'm the crazy one.",
        "I work twice as hard for half the recognition.",
        "This makes me absolutely livid and I'm not apologizing for it.",
        "I'm done being nice to people who don't deserve it.",
        "Nobody takes accountability anymore and it's infuriating.",
        "I was already stressed and then this happened.",
        "They completely disregarded my feelings.",
        "I'm so mad right now I can't even think straight.",
        "I was shaking with anger after that conversation.",
        "They apologized but didn't mean a single word of it.",
        "The fact that nobody sees the problem IS the problem.",
        "I got cut off three times in traffic and my patience is gone.",
        "I'm annoyed that I even have to deal with this.",
        "This whole thing is a massive waste of my time.",
        "Stop making excuses and own up to what you did.",
        "I hate that I care this much about something that doesn't care about me.",
        "I'm over this. Completely over it.",
        "I'm seething and I need to go for a walk before I say something I regret.",
        "The injustice of this situation is absolutely staggering.",
        "They didn't just let me down, they betrayed me.",
        "I'm angry and I have every right to be.",
        "Can you seriously not see how wrong this is.",
        "I'm so irritated by how incompetent this entire process is.",
        "You broke your word and that's not something I take lightly.",
        "Everything is going wrong and I've had it.",
        "I literally cannot deal with this level of stupidity.",
        "I've never felt this much resentment toward someone.",
    ],

    # ============================
    # FEAR - anxiety, dread, panic, vulnerability, worry, overthinking
    # ============================
    "fear": [
        "What if they find out I have no idea what I'm doing.",
        "I can't stop thinking about all the ways this could go wrong.",
        "Every time my phone rings late at night my heart drops.",
        "The doctor said they need to run more tests.",
        "I'm terrified of ending up alone.",
        "Sometimes I lie awake imagining the worst possible outcome.",
        "I froze during the presentation and now I can't stop replaying it.",
        "The thought of starting over at my age is paralyzing.",
        "I keep checking the locks. I know I already checked.",
        "My mind won't stop racing with worst-case scenarios.",
        "What if I'm not enough for this job.",
        "I'm scared to open that email.",
        "I get this sinking feeling every Sunday night before Monday.",
        "I can't breathe properly when I think about the future.",
        "I'm overthinking everything and I can't turn it off.",
        "What if they all find out I'm faking it.",
        "I woke up in a panic and couldn't remember why.",
        "I feel like something bad is about to happen.",
        "My anxiety has been through the roof lately.",
        "I've been avoiding that conversation because the outcome terrifies me.",
        "The uncertainty is killing me more than the actual problem.",
        "I lay awake at 3am worrying about things I can't control.",
        "What if I make the wrong decision and ruin everything.",
        "I had a panic attack in the grocery store today.",
        "I'm dreading tomorrow more than I can express.",
        "I feel unsafe even when logically I know I'm fine.",
        "My hands shake before every meeting and it's getting worse.",
        "What if this is as good as it gets.",
        "I keep replaying that conversation in my head wondering what I said wrong.",
        "I'm afraid I'm turning into someone I don't want to be.",
        "I'm scared of disappointing the people who believe in me.",
        "I've been having nightmares about failing.",
        "I can't shake this feeling of dread.",
        "I'm worried sick about my parents' health.",
        "Every small symptom sends me spiraling.",
        "I'm afraid to get close to anyone because everyone leaves eventually.",
        "My chest tightens every time I walk into that building.",
        "I keep imagining the worst and I can't stop.",
        "I feel like I'm walking on eggshells constantly.",
        "I'm one bad day away from completely falling apart.",
        "I don't know what's around the corner and that scares me.",
        "I can't focus because my brain keeps going to dark places.",
        "What if I'm wrong about everything.",
        "I'm afraid to hope because the disappointment would destroy me.",
        "The panic comes in waves and each one is worse.",
        "I'm terrified of making a mistake that can't be undone.",
        "Something feels off but I can't put my finger on it.",
        "I feel dread in the pit of my stomach and it won't go away.",
        "I'm so stressed about money that I can't sleep.",
        "What if they don't come back.",
        "I'm anxious about things that haven't even happened yet.",
        "I question every decision I make and it's exhausting.",
        "I keep second-guessing myself and it's ruining my confidence.",
        "I feel like I'm standing at the edge of a cliff.",
        "My body tenses up instinctively around certain people.",
        "I'm afraid to look at my bank account.",
        "I had to pull over because my heart was racing so fast.",
        "I'm worried I'll never get over this.",
        "The fear of failure keeps me from even trying.",
        "I feel on edge all the time, like I'm waiting for something to go wrong.",
    ],

    # ============================
    # SURPRISE - shock, astonishment, disbelief, unexpected
    # ============================
    "surprise": [
        "Wait, WHAT? You're telling me this NOW?",
        "I never expected to hear from them again after all these years.",
        "Plot twist — the quiet kid in class is a published author.",
        "I opened the door and everyone was there. I had no clue.",
        "They actually apologized. I'm genuinely speechless.",
        "I checked my bank account and there's an extra deposit I can't explain.",
        "My test results came back completely normal. I was bracing for the worst.",
        "He showed up at my doorstep with flowers after ten years apart.",
        "I got a message from someone I never thought I'd hear from again.",
        "You're kidding me right now. Seriously?",
        "I can't believe this is actually happening.",
        "Out of nowhere the whole office started clapping for me.",
        "I just found out I have a half-sibling I never knew about.",
        "Life just threw me the most unexpected curveball.",
        "My jaw literally dropped when I heard the news.",
        "I walked in and the place was completely transformed. How did they do that?",
        "That was the last person I expected to see at that event.",
        "I opened a book from my childhood and a note from my father fell out.",
        "I'm shook.",
        "I looked at the results three times because I didn't believe them.",
        "My neighbor just casually mentioned they used to be a spy.",
        "She told me she's pregnant and I did NOT see that coming.",
        "I won the raffle. I never win anything. This can't be real.",
        "The twist in that movie blew my mind.",
        "I got the email and had to read it five times to make sure it was real.",
        "Hold on, did I hear you right?",
        "I turned around and there he was, completely out of nowhere.",
        "Wow. I need a minute to process this.",
        "Nobody saw that coming. Nobody.",
        "That was the most unexpected thing that's happened to me all year.",
        "I audibly gasped. In public. No shame.",
        "Wait... you're serious? This isn't a joke?",
        "I can barely wrap my head around what just happened.",
        "The plot twist was incredible, I did not see it coming at all.",
        "Someone I ghosted five years ago just showed up at my work.",
        "My quiet coworker just delivered the most powerful speech I've ever heard.",
        "I walked out of the exam feeling defeated and turns out I aced it.",
        "That's wild. Absolutely wild.",
        "I got the call and I was so shocked I couldn't even respond.",
        "I just stood there, mouth open, completely dumbfounded.",
        "Did that really just happen or am I dreaming.",
        "That revelation changed everything I thought I knew.",
        "What in the world. I'm stunned.",
        "Came home to a surprise I will never forget.",
        "This is the kind of thing you read about but never expect to experience.",
        "I opened the letter and my whole world shifted.",
        "That twist ending left me staring at the ceiling for twenty minutes.",
        "I'm still trying to process what I just witnessed.",
        "Didn't see that one coming, not even close.",
        "My reaction was pure shock. Just pure shock.",
    ],

    # ============================
    # BORED - apathy, restlessness, monotony, numbness, lack of stimulation
    # ============================
    "bored": [
        "I watched the news and felt absolutely nothing.",
        "People keep asking how I am and I don't know what to say because I feel nothing.",
        "I ate because it was lunchtime, not because I was hungry.",
        "Things that used to excite me just feel like noise now.",
        "I'm not sad. I'm not happy. I'm just here.",
        "I scrolled through my phone for three hours and can't remember a single thing.",
        "Someone told me great news and I couldn't even fake a reaction.",
        "I've been staring at this wall for twenty minutes and I don't care.",
        "Too tired to do anything fun but too bored to sleep.",
        "Brain empty. No thoughts. Just existing.",
        "I've opened every app on my phone twice and nothing interests me.",
        "I'm literally just lying here rotting.",
        "I can't even think of something I want to do.",
        "Same routine, same walls, same nothing.",
        "I'm so bored I could watch paint dry and it would be an improvement.",
        "Every day feels like a carbon copy of the one before it.",
        "I need something to happen. Anything. Good, bad, I don't care.",
        "I've been sitting here for an hour and haven't done a single productive thing.",
        "Nothing sounds appealing right now.",
        "I'm stuck in an infinite loop of doing nothing and feeling guilty about it.",
        "I have a list of things to do but zero motivation to do any of them.",
        "Everything feels meh.",
        "I'm so understimulated my brain is practically begging for input.",
        "The highlight of my day was watching the microwave timer count down.",
        "I keep opening the fridge even though I know nothing new is in there.",
        "I've been flipping channels for thirty minutes and nothing holds my attention.",
        "My weekend plans: absolutely nothing. Not by choice.",
        "I feel like a zombie on autopilot.",
        "I've been procrastinating for so long I forgot what I was avoiding.",
        "I'm trapped in the most boring day of my life.",
        "I started three different activities and lost interest in all of them.",
        "Sunday afternoon and I'm just killing time until Monday.",
        "Is it possible to be bored of being bored?",
        "I've refreshed the same page fifteen times hoping for something new.",
        "My energy is at absolute zero today.",
        "I feel completely flat. No highs, no lows, just nothing.",
        "I yawned so hard a tear came out and that was the most I've felt all day.",
        "I have hobbies but none of them sound appealing right now.",
        "I just don't feel like doing anything at all.",
        "I'm existing but not really living today.",
        "I'm in a rut and I can't climb out.",
        "There's nothing to look forward to this week.",
        "I'm counting ceiling tiles. That's where I'm at.",
        "Every conversation feels like it's happening underwater.",
        "I feel emotionally numb and physically restless at the same time.",
        "All the shows I used to love seem boring now.",
        "I could do something productive but I just don't want to.",
        "I woke up and immediately wanted to go back to sleep. Not tired, just uninterested.",
        "I feel like my life is buffering.",
        "My brain is running at 5 percent capacity today.",
        "I need stimulation. This silence is killing me.",
        "Nothing matters and I can't be bothered to care about that fact.",
        "I'm on the couch. I've been on the couch. I will be on the couch.",
        "I'm not depressed. I'm just overwhelmingly bored.",
        "The days blur into each other when nothing changes.",
        "I've been wearing the same sweatpants for three days because what's the point.",
        "My screen time report is embarrassing and I don't even remember any of it.",
        "I've read the same paragraph four times because my brain keeps drifting.",
        "I just want something, ANYTHING, to break up the monotony.",
        "I'm staring at a full bookshelf with nothing to read.",
        "Honestly I'd welcome a minor inconvenience just for the variety.",
        "I feel like I'm wasting my time but also don't care enough to stop.",
        "The world is happening outside and I'm here doing absolutely nothing.",
        "I'm so bored I started organizing my sock drawer.",
        "I feel like furniture. Just here, taking up space.",
        "I went for a walk, came back, and I'm still bored.",
        "I'm literally watching the clock. It's not even moving.",
        "Nothing excites me. Nothing annoys me. I'm just flat.",
        "I'm understimulated and overstimulated at the same time somehow.",
        "Today is forgettable and I haven't even finished it yet.",
        "I've been playing one game on repeat because I can't think of anything else.",
        "I need a hobby. Or a friend. Or a crisis. Something.",
        "I feel like my personality shut off today.",
        "I've been doomscrolling for two hours straight. Send help.",
        "My brain feels like it's running in power saving mode.",
        "I'm not doing anything and I don't plan to.",
        "If boredom was a sport I'd be a world champion.",
        "Even my thoughts are boring right now.",
        "I have access to literally all of human knowledge and I'm still bored.",
        "I feel like time stopped but in the most uninteresting way possible.",
        "I don't feel anything at all and I can't tell if that's okay or not.",
        "The most interesting thing that happened today was a notification about a software update.",
        "I feel blank. Like a factory reset happened on my personality.",
        "My attention span is officially nonexistent.",
        "I tried being productive. Lasted about four minutes.",
        "Sitting here wishing life had a fast forward button.",
        "I'm so checked out right now.",
        "My day has been a flat line. Literally nothing happened.",
        "I feel numb to everything.",
        "I tried meditating but my brain refused to turn off or do anything useful.",
        "Just going through the motions.",
        "I sat through a two-hour meeting and retained zero percent of it.",
        "I've been waiting for inspiration and it clearly took the day off.",
        "I just exist. That's the whole update.",
        "Out of all the days that have existed, this is definitely one of them.",
        "I stared at a menu for ten minutes and still couldn't decide because nothing appealed to me.",
        "Autopilot mode activated.",
        "I'm somewhere between lazy and lifeless.",
    ],

    # ============================
    # NEUTRAL - calm, balanced, focused, stable, observational
    # ============================
    "neutral": [
        "It was an average day. Nothing great, nothing bad.",
        "I finished what I needed to do and went home.",
        "The weather is fine today.",
        "I had leftovers for dinner. They were alright.",
        "Work was normal. Nothing worth mentioning.",
        "I went for a walk. It was nice.",
        "I'm just doing my thing today.",
        "I don't really have strong feelings about it either way.",
        "It is what it is.",
        "I ran some errands and now I'm back.",
        "I watched some TV after work.",
        "I cooked dinner and cleaned up.",
        "The meeting went as expected.",
        "Just another Tuesday.",
        "I'm okay. Not great, not bad, just okay.",
        "Had a quiet morning reading the paper.",
        "I caught the earlier train today which was nice.",
        "I'm just going with the flow.",
        "Everything is stable. Steady.",
        "I handled the tasks on my to-do list efficiently.",
        "I feel calm and present right now.",
        "The project is on track and I'm not stressed about it.",
        "I'm content with how things are going.",
        "I spent the morning focusing on deep work. It was productive.",
        "Just finished yoga and I feel balanced.",
        "I meditated for ten minutes and I feel centered.",
        "I don't need anything right now — everything is fine as is.",
        "I had a quiet evening at home and it was exactly what I needed.",
        "I'm at peace with where things stand.",
        "I read a chapter of my book during lunch.",
        "Nothing to report. Just a regular day.",
        "I made my bed, brewed some tea, and started working.",
        "Things are going according to plan.",
        "I observed the birds in the yard this morning.",
        "I'm in a steady head space today.",
        "Just maintaining my routine.",
        "I completed the task without any issues.",
        "The commute was smooth today.",
        "My mind is clear.",
        "Yes, that sounds fine.",
        "I'm feeling pretty balanced right now.",
        "I have no complaints today.",
        "Took a slow morning and it set a good tone for the day.",
        "I'm good. Nothing feels urgent or overwhelming.",
        "Just taking things one step at a time.",
        "I cleaned the apartment and it feels refreshing.",
        "My focus was good today. Got through my tasks without distraction.",
        "I noticed the trees are changing color. Interesting.",
        "Just thinking about what to have for lunch.",
        "I read some articles during my break.",
        "Everything feels manageable today.",
        "I had a conversation with a colleague about work procedures.",
        "I watered the plants and checked mail.",
        "Nothing noteworthy, which is sometimes the best kind of day.",
        "I ate breakfast, brushed my teeth, and started my day.",
        "I'm present but not particularly engaged or disengaged.",
        "The morning was slow. The afternoon was productive.",
        "I don't feel one way or another about it.",
        "I took a walk around the block at lunch. Fresh air was nice.",
        "I'm performing well at work but not over-exerting myself.",
        "Everything is operating as usual.",
        "I learned something new today. That was satisfying.",
        "I'm reflecting on the day and it was pretty uneventful.",
        "Looking forward to a quiet weekend.",
        "I feel grounded today.",
        "Just living day to day.",
        "I'm relaxed and present.",
        "I finished my workout and feel composed.",
        "I had green tea and journaled for a few minutes.",
        "My energy is even today. Not high, not low.",
        "I'm focused. My work is flowing well.",
        "I caught up on emails and cleared my inbox.",
        "All in all, a fairly standard day.",
        "I feel stable and that's enough.",
        "I cooked a new recipe. It turned out decent.",
        "Currently listening to music and organizing my desk.",
        "I'm okay with the pace of things right now.",
        "Took the scenic route today. It was pleasant.",
        "I'm not in a rush. Everything can wait.",
        "Just doing what needs to be done.",
    ],
}


def generate():
    rows = []
    for label, texts in templates.items():
        for text in texts:
            rows.append({"text": text, "label": label})

    random.seed(42)
    random.shuffle(rows)

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["text", "label"])
        writer.writeheader()
        writer.writerows(rows)

    print(f"✅ Generated {len(rows)} V5 synthetic samples → {OUTPUT_PATH}")
    print(f"\nLabel distribution:")
    from collections import Counter
    counts = Counter(r["label"] for r in rows)
    for label, count in sorted(counts.items()):
        print(f"  {label:20s} {count}")


if __name__ == "__main__":
    generate()
