from app.services.chroma_service import chroma_service
from app.services.microtask_agent import microtask_agent
from app.services.llm_service import llm_service
import random

class PlannerAgent:
    def generate_plan(self, mood: str, intensity: float, time_minutes: int, preferences: dict):
        # Map detected mood to target content mood
        target_mood_map = {
            "boredom": "excitement",
            "sadness": "comfort",
            "joy": "joy",
            "anger": "relaxation",
            "fear": "calm",
            "optimism": "productivity",
             # labels from twitter-roberta
             "joy": "celebration",
             "sadness": "uplifting",
             "anger": "calm",
             "optimism": "progress",
             "low_energy": "energizing"
        }
        
        target_query = target_mood_map.get(mood, "general")
        
        # Query Vector DB
        activities = chroma_service.query_activities(query_text=target_query, n_results=5)
        
        plan = []
        
        # 1. Calibration (Breathing)
        plan.append({
            "type": "breathing",
            "description": "Do a 2-minute breathing reset. Inhale 4s, hold 4s, exhale 4s.",
            "time_minutes": 2
        })
        
        # 2. Micro Task (from Agent)
        mt_result = microtask_agent.generate(mood=mood)
        plan.append({
             "type": "micro_task",
             "description": mt_result['micro_task'],
             "time_minutes": 1,
             "metadata": {"category": mt_result['category']}
        })
             
        # 3. Main Activity (from RAG)
        if activities['documents'] and activities['documents'][0]:
             candidates = activities['documents'][0]
             meta = activities['metadatas'][0]
             idx = random.randint(0, min(len(candidates)-1, 2))
             
             plan.append({
                 "type": "activity",
                 "description": candidates[idx],
                 "time_minutes": meta[idx].get('time_minutes', 15),
                 "metadata": meta[idx]
             })
        else:
            # Fallback if DB empty
            plan.append({
                 "type": "activity",
                 "description": "Go for a short walk outside.",
                 "time_minutes": 10
             })
             
        # 4. Music Recommendation
        # In a real agent, this would query the music service
        plan.append({
            "type": "music",
            "description": f"Play a short {target_query} track to boost the mood.",
            "time_minutes": 3
        })
        
        # 5. Positive Affirmation (Generated by LLM)
        try:
             affirmation = llm_service.generate(
                system_prompt="You are a motivational coach. Generate a short, powerful affirmation (max 10 words) for someone feeling " + mood,
                user_prompt="Generate affirmation",
                model="mistralai/mistral-7b-instruct:free"
             )
             # Fallback if empty or error
             if not affirmation or "error" in affirmation.lower():
                 affirmation = "You are capable of amazing things."
        except:
             affirmation = "Small steps lead to big changes."

        plan.append({
            "type": "affirmation",
            "description": affirmation.strip('"'),
            "time_minutes": 1
        })
        
        return {
            "plan": plan,
            "source": "rag+llm_planner_agent"
        }

planner_agent = PlannerAgent()
